---
title: bodemboerderij
layout: layouts/article.html
---

Boskanter is (zoals veel permacultuur- en bioboerderijen) een bodemboerderij. Naast vruchten telen we ook bodem. We concentreren de biomassa (hout en groen) uit gans Boskanter (40.000 m²) in de moestuin (4.000 m²). We doen dat onder de vorm van gecomposteerde mest van onze schapen, kippen en paard, via mulch en houtskool. De bedoeling is dat de vruchtbare bodem, ondanks de oogst, toeneemt. De biomassa van de omdringende natuur wordt door de planten steeds aangevuld. Met mineralen die door de boomwortels diep uit de ondergrond worden opgehaald en de basiselementen van het leven die door water en lucht worden aangevoerd, tovert de energie van de zon steeds nieuwe scheuten en ontluikende knoppen. We zoeken voor die natuur een beheer dat de biodiversiteit ondersteunt. Dat komt ook de gezondheid van de moestuin ten goede. 
## Een eindige grondstof
Vruchtbare bodem is een eindige grondstof die we in sneltempo verbruiken en die ons erg veel diensten levert. Ze wordt op dit ogenblik door geen enkel verdrag beschermd. Haar buffer kan ons nochtans voor veel onheil behoeden. In de eerste plaats het veranderend klimaat. In de bodem kan het grootste deel van de overtollige koolstof gecapteerd worden onder de vorm van stabiele humus. Die humus houdt ook water en voedingsstoffen vast zodat de planten er beroep op kunnen doen als ze ze nodig hebben en ze verbetert de structuur van de bodem, zowal als die te los (zand) als te vast (klei) is. Met de huidige landbouwmethoden doen we het tegenovergestelde. Door de intensieve bewerking valt de humus uiteen en komt de koolstof terug in de atmosfeer. Danzij de industriële productie van stikstof op basis van aardolie kunnen we ook zonder humus blijven produceren.
## Kleinschalige experimenten …
Wie anders wil werken stoot op een financieringssysteem dat de bestaande manier van werken in stand houdt. Met andere subsidie spelregels kan een landbouw die de bodem respecteert en de bevolking gezond voedt ook rendabel zijn. Zo’n log schip van richting doen veranderen zonder garanties voor de haalbaarheid is natuurlijk spannend. Daarom moet er (legale, financiële) ruimte gecreëerd worden en land ter beschikking gesteld worden van kleine onafhankelijke bodemboerderijtjes die nieuwe technieken uitproberen en de wereld hiermee laten kennismaken.
## Productie?
Op Boskanter ‘boeren’ we in de eerste plaats om bezoekers de kans te geven te leren en te beleven, dus niet om te produceren voor verkoop.
